### PR TITLE
Fixes, extensions path problem and problem with array of social buttons

### PR DESCRIPTION
**Pull request by dactivo**
I have found the following problems with your extension, I hope this is useful for you:

1.-First change is that there is an equal instead of two equals, I suppose this is a bug, because I haven't used it.

2.-I have added a replace function in the event where the result of:
$this->app['resources']->getUrl('root') . $this->config['path']
Is "whatever/" + "/", creating the path: "//" which gives me an error to retrieve the js as it looks for: 

http://extensions/vendor/bolt/.....

I found the same problem with the plugin editable, and Rix beck accepted the change:

https://github.com/rixbeck/bolt-extension-editable/issues/11

3.-When you want to pass more than one network in the function socialite, I write this:
{{ socialite(['TwitterShare', .... ,....]) }}

In the code, the loop only takes the first one, because once you use the "return", the second is forgotten.
This is why in the code, instead of returning, I do a concat.

Hope this helps. Bolt rocks!

### CODE REVIEW

**Comment by GawainLynch** [comment]
I am on a train crossing the country... Because birthday party... But I will look tomorrow... On the surface your changes look very good (and I apparently can't type/code) :grin:

**Comment by dactivo** [comment]
:-) :+1:  you are doing a great job and it's a pleasure to collaborate. Nice trip!

**Comment by GawainLynch** [comment]
:+1:

**Comment by GawainLynch** [comment]
The asset handling wasn't up-to-date as this extension goes back a long way… So added that to your update and tagged 2.1.4!

**Pull request merged**
